INSERT INTO PERSON(ID, NAME, AGE, USERNAME) VALUES (100, 'Alice', 20, 'alice');
INSERT INTO PERSON(ID, NAME, AGE, USERNAME) VALUES (101, 'Bob', 21, 'bob');
INSERT INTO PERSON(ID, NAME, AGE, USERNAME) VALUES (102, 'John', 30, 'john');
INSERT INTO PERSON(ID, NAME, AGE, USERNAME) VALUES (103, 'Jane', 25, 'jane');